---
version: 2.1
orbs:
  slack: circleci/slack@4.8.3
jobs:
  ensure_formatting:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: poetry install
      - run:
          name: confirm black version
          command: poetry run black --version
      - run:
          name: run isort check
          command: poetry run isort --check-only .
      - run:
          name: run black check
          command: poetry run black --check .
      - slack/notify:
          branch_pattern: master
          event: fail
          template: basic_fail_1
  linter:
    docker:
      - image: alpine/flake8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: flake8
          command: flake8 --ignore=E,W ~/repo
      - slack/notify:
          branch_pattern: master
          event: fail
          template: basic_fail_1
  tests:
    parameters:
      version:
        default: "3.9"
        type: string
    docker:
      - image: cimg/python:<< parameters.version >>
    steps:
      - checkout
      - run:
          name: install dependencies
          command: poetry install
      - run:
          name: run pytest
          command: poetry run pytest --cov=pycti
      - slack/notify:
          branch_pattern: master
          event: fail
          template: basic_fail_1
  build:
    working_directory: ~/opencti-client
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: install dependencies
          command: poetry install
      - run:
          name: check version
          command: |
            package_version="$(poetry version --no-ansi)"
            [ "${CIRCLE_TAG}" = "${package_version}" ] \
              || printf "Version mismatch: %s is not equal to %s\n" \
                 "${CIRCLE_TAG}" "${package_version}"
      - run:
          name: build
          command: >
            SOURCE_DATE_EPOCH="$(git log -1 --pretty=%ct)" poetry build
      - slack/notify:
          branch_pattern: master
          event: fail
          template: basic_fail_1
      - persist_to_workspace:
          root: ~/opencti-client
          paths:
            - dist
  deploy:
    working_directory: ~/opencti-client
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - attach_workspace:
          at: ~/opencti-client
      - run:
          name: configure pypi credentials
          command: poetry config http-basic.pypi opencti "${PYPI_PASSWORD}"
      - run:
          name: upload to pypi
          command: poetry publish
      - slack/notify:
          branch_pattern: master
          event: fail
          template: basic_fail_1
  notify_rolling:
    docker:
      - image: "cimg/base:stable"
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1
  notify:
    docker:
      - image: "cimg/base:stable"
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  version: 2
  opencti_client_python:
    jobs:
      - ensure_formatting:
          filters:
            tags:
              only: /.*/
      - linter:
          filters:
            tags:
              only: /.*/
      - tests:
          name: tests_37
          filters:
            tags:
              only: /.*/
          version: "3.7"
      - tests:
          name: tests_38
          filters:
            tags:
              only: /.*/
          version: "3.8"
          requires:
            - tests_37
      - tests:
          name: tests_39
          filters:
            tags:
              only: /.*/
          version: "3.9"
          requires:
            - tests_38
      - tests:
          name: tests_310
          filters:
            tags:
              only: /.*/
          version: "3.10"
          requires:
            - tests_39
      - build:
          filters:
            tags:
              only: /.*/
          requires:
            - ensure_formatting
            - linter
            - tests_310
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+(\.[0-9]+)([a-z]?)*/
            branches:
              ignore: /.*/
      - notify_rolling:
          requires:
            - build
      - notify:
          requires:
            - deploy
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+(\.[0-9]+)*/
            branches:
              ignore: /.*/